####
POST http://localhost:3005/submit-attendance
Content-Type: application/json

{  "date": "2025-03-16",
  "array": [
  {
    "child_id": 1, "status": false
  },
  {
    "child_id": 2, "status": false
  },
  {
    "child_id": 3, "status": true
  },
  {
    "child_id": 4, "status": true
  },
  {
    "child_id": 5, "status": false
  },
  {
    "child_id": 6, "status": true
  },
  {
    "child_id": 7, "status": false
  },
  {
    "child_id": 8, "status": true
  },
  {
    "child_id": 9, "status": false
  },
  {
    "child_id": 10, "status": true
  },
  {
    "child_id": 11, "status": false
  },
  {
    "child_id": 12, "status": false
  }
]}

###
POST http://localhost:3005/date-attendance 
Content-Type: application/json

{
"date": "2025-02-16"
}

###
GET http://localhost:3005/attendance-details
Content-Type: application/json

###
GET http://localhost:3005/dates
Content-Type: application/json

###
DELETE http://localhost:3005/delete-attendance
Content-Type: application/json

{
  "date": "2024-12-22"
}

###
GET http://localhost:3005/services
Content-Type: application/json
