-- CREATE TABLE children(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name STRING, gender STRING);
-- INSERT INTO children(name, gender) VALUES("NAGA CHAITHANYA JANIPELLA", "MALE"), ("LAXMI TEJA NITHIPUDI", "MALE"), ("DHARSHIT KARTHIK BHOLA", "MALE");

-- CREATE TABLE attendance(child_id INTEGER, date DATE, status BOOLEAN DEFAULT false, FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE);
-- UPDATE children SET name = "SANTHOSH DHANAM" WHERE id = 9;
SELECT DISTINCT date FROM attendance;